version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/application/Dockerfile
    working_dir: /var/www/html
    tty: true
    ports:
      - 8080:80
      - 443:443
    links:
      - database
      - maildev
    depends_on:
      - maildev
      - database
    volumes:
      - ./htdocs:/var/www/html

  database:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: pixel
      MYSQL_USER: pixel_user
      MYSQL_PASSWORD: pixel_secret
      MYSQL_ROOT_PASSWORD: root_secret
    ports:
      - 3306:3306
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
    ports:
      - 8000:80
    links:
      - database
  elasticsearch:
    image: elasticsearch:2.4.6-alpine
    ports:
      - 9200:9200
      - 9300:9300
  maildev:
    image: djfarrelly/maildev
    ports:
      - 8001:80
  vue:
   image: ebiven/vue-cli
   volumes:
      - ./htdocs:/var/www/html
   ports:
      - 8002:8080

